name: IPTV Update Every 4 Hours

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run update script
        run: node index.js

      - name: Commit and Push M3U file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # playlist.m3u ရှိမရှိ အရင်စစ်ပြီးမှ add လုပ်မယ်
          if [ -f playlist.m3u ]; then
            git add playlist.m3u
            git commit -m "Auto Update Playlist" || echo "No changes to commit"
            git push
          else
            echo "Error: playlist.m3u not found!"
            exit 1
          fi
